# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fts_analysis_pipeline.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66ts_analysis_pipeline.proto\x12\x0f\x61\x65\x63\x61.rpc.db.fts\"\"\n\x0bProfileInfo\x12\x13\n\x0b\x64uration_us\x18\x01 \x01(\x04\"k\n\x18PipelineExecutionRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12\x12\n\nindex_name\x18\x02 \x01(\t\x12\x13\n\x0b\x66ield_names\x18\x03 \x03(\t\x12\r\n\x05query\x18\x04 \x01(\t\"j\n\x19PipelineExecutionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\t\x12-\n\x07profile\x18\x03 \x01(\x0b\x32\x1c.aeca.rpc.db.fts.ProfileInfo\"Y\n\x1d\x41\x64hocPipelineExecutionRequest\x12\x14\n\x0cpipeline_def\x18\x01 \x01(\t\x12\x13\n\x0b\x66ield_names\x18\x02 \x03(\t\x12\r\n\x05query\x18\x03 \x01(\t\"o\n\x1e\x41\x64hocPipelineExecutionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\t\x12-\n\x07profile\x18\x03 \x01(\x0b\x32\x1c.aeca.rpc.db.fts.ProfileInfo2\xf4\x01\n\x1a\x46TSAnalysisPipelineService\x12\x62\n\x07\x65xecute\x12).aeca.rpc.db.fts.PipelineExecutionRequest\x1a*.aeca.rpc.db.fts.PipelineExecutionResponse\"\x00\x12r\n\rexecute_adhoc\x12..aeca.rpc.db.fts.AdhocPipelineExecutionRequest\x1a/.aeca.rpc.db.fts.AdhocPipelineExecutionResponse\"\x00\x42\x03\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fts_analysis_pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_PROFILEINFO']._serialized_start=48
  _globals['_PROFILEINFO']._serialized_end=82
  _globals['_PIPELINEEXECUTIONREQUEST']._serialized_start=84
  _globals['_PIPELINEEXECUTIONREQUEST']._serialized_end=191
  _globals['_PIPELINEEXECUTIONRESPONSE']._serialized_start=193
  _globals['_PIPELINEEXECUTIONRESPONSE']._serialized_end=299
  _globals['_ADHOCPIPELINEEXECUTIONREQUEST']._serialized_start=301
  _globals['_ADHOCPIPELINEEXECUTIONREQUEST']._serialized_end=390
  _globals['_ADHOCPIPELINEEXECUTIONRESPONSE']._serialized_start=392
  _globals['_ADHOCPIPELINEEXECUTIONRESPONSE']._serialized_end=503
  _globals['_FTSANALYSISPIPELINESERVICE']._serialized_start=506
  _globals['_FTSANALYSISPIPELINESERVICE']._serialized_end=750
# @@protoc_insertion_point(module_scope)
