# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aeca.protobuf.fts_analysis_pipeline_pb2 as fts__analysis__pipeline__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fts_analysis_pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FTSAnalysisPipelineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.execute = channel.unary_unary(
                '/aeca.rpc.db.fts.FTSAnalysisPipelineService/execute',
                request_serializer=fts__analysis__pipeline__pb2.PipelineExecutionRequest.SerializeToString,
                response_deserializer=fts__analysis__pipeline__pb2.PipelineExecutionResponse.FromString,
                _registered_method=True)
        self.execute_adhoc = channel.unary_unary(
                '/aeca.rpc.db.fts.FTSAnalysisPipelineService/execute_adhoc',
                request_serializer=fts__analysis__pipeline__pb2.AdhocPipelineExecutionRequest.SerializeToString,
                response_deserializer=fts__analysis__pipeline__pb2.AdhocPipelineExecutionResponse.FromString,
                _registered_method=True)


class FTSAnalysisPipelineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def execute_adhoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FTSAnalysisPipelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'execute': grpc.unary_unary_rpc_method_handler(
                    servicer.execute,
                    request_deserializer=fts__analysis__pipeline__pb2.PipelineExecutionRequest.FromString,
                    response_serializer=fts__analysis__pipeline__pb2.PipelineExecutionResponse.SerializeToString,
            ),
            'execute_adhoc': grpc.unary_unary_rpc_method_handler(
                    servicer.execute_adhoc,
                    request_deserializer=fts__analysis__pipeline__pb2.AdhocPipelineExecutionRequest.FromString,
                    response_serializer=fts__analysis__pipeline__pb2.AdhocPipelineExecutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aeca.rpc.db.fts.FTSAnalysisPipelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aeca.rpc.db.fts.FTSAnalysisPipelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FTSAnalysisPipelineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aeca.rpc.db.fts.FTSAnalysisPipelineService/execute',
            fts__analysis__pipeline__pb2.PipelineExecutionRequest.SerializeToString,
            fts__analysis__pipeline__pb2.PipelineExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def execute_adhoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aeca.rpc.db.fts.FTSAnalysisPipelineService/execute_adhoc',
            fts__analysis__pipeline__pb2.AdhocPipelineExecutionRequest.SerializeToString,
            fts__analysis__pipeline__pb2.AdhocPipelineExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
