# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workspaces.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10workspaces.proto\x12\x08\x61\x65\x63\x61.rpc\"0\n\x16\x43reateWorkspaceRequest\x12\x16\n\x0eworkspace_name\x18\x01 \x01(\t\"\x8a\x01\n\x17\x43reateWorkspaceResponse\x12\x38\n\x06status\x18\x01 \x01(\x0e\x32(.aeca.rpc.CreateWorkspaceResponse.Status\"5\n\x06Status\x12\x0b\n\x07Invalid\x10\x00\x12\x0b\n\x07Success\x10\x01\x12\x11\n\rAlreadyExists\x10\x02\".\n\x14\x44ropWorkspaceRequest\x12\x16\n\x0eworkspace_name\x18\x01 \x01(\t\"s\n\x15\x44ropWorkspaceResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.aeca.rpc.DropWorkspaceResponse.Status\"\"\n\x06Status\x12\x0b\n\x07Invalid\x10\x00\x12\x0b\n\x07Success\x10\x01\"\x17\n\x15ListWorkspacesRequest\"9\n\tWorkspace\x12\x14\n\x0cworkspace_id\x18\x01 \x01(\r\x12\x16\n\x0eworkspace_name\x18\x02 \x01(\t\"\x9e\x01\n\x16ListWorkspacesResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.aeca.rpc.ListWorkspacesResponse.Status\x12\'\n\nworkspaces\x18\x02 \x03(\x0b\x32\x13.aeca.rpc.Workspace\"\"\n\x06Status\x12\x0b\n\x07Invalid\x10\x00\x12\x0b\n\x07Success\x10\x01\x32\x9b\x02\n\x11WorkspacesService\x12Y\n\x10\x63reate_workspace\x12 .aeca.rpc.CreateWorkspaceRequest\x1a!.aeca.rpc.CreateWorkspaceResponse\"\x00\x12S\n\x0e\x64rop_workspace\x12\x1e.aeca.rpc.DropWorkspaceRequest\x1a\x1f.aeca.rpc.DropWorkspaceResponse\"\x00\x12V\n\x0flist_workspaces\x12\x1f.aeca.rpc.ListWorkspacesRequest\x1a .aeca.rpc.ListWorkspacesResponse\"\x00\x42\x03\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workspaces_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_CREATEWORKSPACEREQUEST']._serialized_start=30
  _globals['_CREATEWORKSPACEREQUEST']._serialized_end=78
  _globals['_CREATEWORKSPACERESPONSE']._serialized_start=81
  _globals['_CREATEWORKSPACERESPONSE']._serialized_end=219
  _globals['_CREATEWORKSPACERESPONSE_STATUS']._serialized_start=166
  _globals['_CREATEWORKSPACERESPONSE_STATUS']._serialized_end=219
  _globals['_DROPWORKSPACEREQUEST']._serialized_start=221
  _globals['_DROPWORKSPACEREQUEST']._serialized_end=267
  _globals['_DROPWORKSPACERESPONSE']._serialized_start=269
  _globals['_DROPWORKSPACERESPONSE']._serialized_end=384
  _globals['_DROPWORKSPACERESPONSE_STATUS']._serialized_start=166
  _globals['_DROPWORKSPACERESPONSE_STATUS']._serialized_end=200
  _globals['_LISTWORKSPACESREQUEST']._serialized_start=386
  _globals['_LISTWORKSPACESREQUEST']._serialized_end=409
  _globals['_WORKSPACE']._serialized_start=411
  _globals['_WORKSPACE']._serialized_end=468
  _globals['_LISTWORKSPACESRESPONSE']._serialized_start=471
  _globals['_LISTWORKSPACESRESPONSE']._serialized_end=629
  _globals['_LISTWORKSPACESRESPONSE_STATUS']._serialized_start=166
  _globals['_LISTWORKSPACESRESPONSE_STATUS']._serialized_end=200
  _globals['_WORKSPACESSERVICE']._serialized_start=632
  _globals['_WORKSPACESSERVICE']._serialized_end=915
# @@protoc_insertion_point(module_scope)
