# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import aeca.protobuf.workspaces_pb2 as workspaces__pb2


class WorkspacesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_workspace = channel.unary_unary(
                '/aeca.rpc.WorkspacesService/create_workspace',
                request_serializer=workspaces__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=workspaces__pb2.CreateWorkspaceResponse.FromString,
                )
        self.drop_workspace = channel.unary_unary(
                '/aeca.rpc.WorkspacesService/drop_workspace',
                request_serializer=workspaces__pb2.DropWorkspaceRequest.SerializeToString,
                response_deserializer=workspaces__pb2.DropWorkspaceResponse.FromString,
                )
        self.list_workspaces = channel.unary_unary(
                '/aeca.rpc.WorkspacesService/list_workspaces',
                request_serializer=workspaces__pb2.ListWorkspacesRequest.SerializeToString,
                response_deserializer=workspaces__pb2.ListWorkspacesResponse.FromString,
                )


class WorkspacesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_workspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def drop_workspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_workspaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkspacesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_workspace': grpc.unary_unary_rpc_method_handler(
                    servicer.create_workspace,
                    request_deserializer=workspaces__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=workspaces__pb2.CreateWorkspaceResponse.SerializeToString,
            ),
            'drop_workspace': grpc.unary_unary_rpc_method_handler(
                    servicer.drop_workspace,
                    request_deserializer=workspaces__pb2.DropWorkspaceRequest.FromString,
                    response_serializer=workspaces__pb2.DropWorkspaceResponse.SerializeToString,
            ),
            'list_workspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.list_workspaces,
                    request_deserializer=workspaces__pb2.ListWorkspacesRequest.FromString,
                    response_serializer=workspaces__pb2.ListWorkspacesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aeca.rpc.WorkspacesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkspacesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_workspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aeca.rpc.WorkspacesService/create_workspace',
            workspaces__pb2.CreateWorkspaceRequest.SerializeToString,
            workspaces__pb2.CreateWorkspaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def drop_workspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aeca.rpc.WorkspacesService/drop_workspace',
            workspaces__pb2.DropWorkspaceRequest.SerializeToString,
            workspaces__pb2.DropWorkspaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list_workspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aeca.rpc.WorkspacesService/list_workspaces',
            workspaces__pb2.ListWorkspacesRequest.SerializeToString,
            workspaces__pb2.ListWorkspacesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
